# Safe
mppi_human_following:
  ros__parameters:
    base_link_frame: 'base_link'
    min_vel_x: -1.0
    max_vel_x: 1.5
    min_vel_y: -1.0
    max_vel_y: 1.0
    min_ang_z: -0.5
    max_ang_z: 0.5
    angle_weight: 10.0
    cbf_weight: 10000000.0
    obs_weight: 10000000.0
    dist_weight_x: 30.0
    dist_weight_y: 20.0
    lambda_weight: 5.0
    safety_length: 0.9 # (meter)
    safety_width: 0.6 # (meter)
    alpha_cbf: 0.3
    odom_topic: /zed_multi/zed_vlm/odom
