actor_control:
  ros__parameters:
      position_control_mode: True
      topic_actor_velocity: cmd_vel_actor
      topic_actor_position: pose_control_actor
      topic_actor_position_mode: mode_position_actor
      topic_actor_global_pose: human_global_pose
      topic_actor_local_pose: human_local_pose
      speed: 0.9
      waypoints: "[[50.0, 0.0, 0.0]]"
      semi_major_axis: 1.2
      semi_minor_axis: 0.9
      num_points: 9
      scenario: s4


